services:
  loki:
    container_name: ${LZ}_loki_${ENV}
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      # Mount named volume containing loki-config.yaml
      - ${LZ}_loki_config_${ENV}:/etc/loki:rw
      # Mount for Loki's persistent data storage
      - ${LZ}_loki_data_${ENV}:/rw
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped
    networks:
      - local_network

  grafana:
    container_name: ${LZ}_grafana_${ENV}
    user: ${UID}:${GID}
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped	
    depends_on:
      - loki
    volumes:
      - ${LZ}_grafana_data_${ENV}:/var/lib/grafana:rw
    networks:
      - local_network

  watchtower:
    container_name: ${LZ}_watchtower_${ENV}
    image: containrrr/watchtower:latest
    environment:
      TZ: US/Central
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_SCHEDULE: "0 9 15-23 * * *"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: telegram://${TELEGRAM_BOT_TOKEN}@telegram/?channels=${TELEGRAM_CHAT_ID}
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- if .Report.Updated -}}
            Container updates detected:
            {{- range .Report.Updated}}
            - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} → {{.LatestImageID.ShortID}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
    restart: unless-stopped
    depends_on:
      - loki
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${LZ}_watchtower_config_${ENV}:/config.json:ro
    networks:
      - local_network

# External network must exist as attachable
networks:
  local_network:
    name: "${LZ}_network_${ENV}"
    external: true

# Named volumes with per-env isolation
volumes:
  ${LZ}_loki_config_${ENV}:
  ${LZ}_loki_data_${ENV}:
  ${LZ}_grafana_data_${ENV}:
  ${LZ}_watchtower_config_${ENV}: