version: '3'

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task: help
  du:
    desc: "Launch Seeker Docker environment (default: dev)"
    vars:
      ENV: '{{default "dev" .CLI_ARGS}}'
    cmds:
      - docker compose --env-file env/{{.ENV}}.env up -d

  dd:
    desc: "Stop Seeker Docker environment"
    vars:
      ENV: '{{default "dev" .CLI_ARGS}}'
    cmds:
      - docker compose --env-file env/{{.ENV}}.env down

  dr:
    desc: "Rebuild Seeker Docker environment"
    vars:
      ENV: '{{default "dev" .CLI_ARGS}}'
    deps: [dd]
    cmds:
      - task: du
        vars: { ENV: '{{.ENV}}' }

  gh:
    desc: "Open project repository in GitHub"
    cmds:
      - open https://github.com/aleonard9/seeker
    silent: true
